### ISSUE TITLE
Add Cadify Web Control - Opens on separate screen

### ISSUE THREAD

**Issue by Constellation-Analytics** [Cadify/User-Reported-Bugs#5]
When using multiple monitors, the option to add a new web control opens on a seperate monitor. 

<img width="1924" height="2160" alt="Image" src="https://github.com/user-attachments/assets/aa5e7365-faee-4b4a-9903-5f9007e5dc2d" />

**Comment by szucsim** [comment]
Thank you for reporting this issue. We have addressed it, and it is now working properly in version [2.15.0.8](https://www.dropbox.com/scl/fi/l2m9bvnml71otb7g3nfuh/CadifySetup.msi?rlkey=qws30gp194abw6arl0iwcomx8&st=skyyjoeq&dl=1)

**Comment by Constellation-Analytics** [comment]
Hi Imre, I am sorry to inform you that I am still encountering this issue.

**Comment by Constellation-Analytics** [comment]
Sorry Imre, this issue is still present. Can you please reopen thie issue. 

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/98e8a11c-6fa3-47f2-984c-f70b2c14c72b" />

**Comment by szucsim** [comment]
@Constellation-Analytics 
Thanks for your feedback. I can already see the issue, this window was overlooked in the updates.

**Comment by szucsim** [comment]
Should be fixed now in latest version. `v2.16.0.17`

**Comment by Constellation-Analytics** [comment]
Thanks I'll let you know. 
From memory there were a couple of screens with this issue. If it arises again I'll take note of the screens and let you know

**Comment by Constellation-Analytics** [comment]
These screens still open on a seperate screen: 
<img width="424" height="219" alt="Image" src="https://github.com/user-attachments/assets/53069386-c4f6-43b5-b1d1-e8e2269a6858" />

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/007c21fb-37d7-492c-9410-a4bf775bc557" />

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/5546cb7a-e3bd-4dd1-b5b4-d3d3739e43fa" />

**Comment by szucsim** [comment]
Included a change on Window handling. [v2.16.0.19](https://www.dropbox.com/scl/fi/l2m9bvnml71otb7g3nfuh/CadifySetup.msi?rlkey=qws30gp194abw6arl0iwcomx8&st=xy9trkky&dl=0)

**Comment by Constellation-Analytics** [comment]
Sorry @szucsim this is still present for all the previously mentioned windows.

**Comment by szucsim** [comment]
I have applied changes to the window handling, please check if the issue still persists. If so, please also check the new About form under the menu: "Help" -> "About". It has been created using a different approach, so if it works correctly, I will know in which direction to proceed with the other windows. Changes have been applied in v2.19.0.1, which is available for [download](https://www.dropbox.com/scl/fi/l2m9bvnml71otb7g3nfuh/CadifySetup.msi?rlkey=qws30gp194abw6arl0iwcomx8&dl=0)
 and installation.

**Comment by Constellation-Analytics** [comment]
https://github.com/user-attachments/assets/ad308c53-a181-4214-80df-6d29bf870230

**Comment by Constellation-Analytics** [comment]
https://github.com/user-attachments/assets/1181becb-34e6-4e54-b60c-3ce1bd25c2ac

**Comment by szucsim** [comment]
@Constellation-Analytics  Applied a simple change to handle window openings. If it does not work, we have a working solution as demonstrated in the second video, but that would require a larger development effort, so it will probably only be included in the April release.

[Download v2.19.0.2]()
